find_path(MBEDTLS_INCLUDE_DIR NAMES mbedtls/ssl.h PATH_SUFFIXES include)

find_library(MBEDTLS_LIBRARY NAMES mbedtls PATH_SUFFIXES lib)
find_library(MBEDX509_LIBRARY NAMES mbedx509 PATH_SUFFIXES lib)
find_library(MBEDCRYPTO_LIBRARY NAMES mbedcrypto PATH_SUFFIXES lib)

set(MBEDTLS_LIBRARIES "${MBEDTLS_LIBRARY}" "${MBEDX509_LIBRARY}" "${MBEDCRYPTO_LIBRARY}")

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(MBEDTLS DEFAULT_MSG
    MBEDTLS_INCLUDE_DIR MBEDTLS_LIBRARY MBEDX509_LIBRARY MBEDCRYPTO_LIBRARY)

mark_as_advanced(MBEDTLS_INCLUDE_DIR MBEDTLS_LIBRARY MBEDX509_LIBRARY MBEDCRYPTO_LIBRARY)

add_library(MbedTLS::TLS UNKNOWN IMPORTED)
set_target_properties(MbedTLS::TLS PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${MBEDTLS_INCLUDE_DIR}"
  IMPORTED_LINK_INTERFACE_LANGUAGES "C"
  IMPORTED_LOCATION "${MBEDTLS_LIBRARY}")

add_library(MbedTLS::Crypto UNKNOWN IMPORTED GLOBAL)
set_target_properties(MbedTLS::Crypto PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${MBEDTLS_INCLUDE_DIR}"
  IMPORTED_LINK_INTERFACE_LANGUAGES "C"
  IMPORTED_LOCATION "${MBEDCRYPTO_LIBRARY}")

add_library(MbedTLS::X509 UNKNOWN IMPORTED GLOBAL)
set_target_properties(MbedTLS::X509 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${MBEDTLS_INCLUDE_DIR}"
  IMPORTED_LINK_INTERFACE_LANGUAGES "C"
  IMPORTED_LOCATION "${MBEDX509_LIBRARY}")
